### ISSUE TITLE
Drupal 7 core problem with *.info files on node_modules folder

### ISSUE THREAD

**Issue by azenkovets** [ADCI/webpack-starter-kit#1]
Please add these lines to package.json

`"scripts": {
  "postinstall": "find node_modules/ -name '*.info' -type f -delete"
}`

This script will remove all *.info files from node_modules folder and subfolders

You can find more info about this issue here: http://kevinquillen.com/drupal/2015/06/10/fixing-segfault-in-drupal

**Comment by guryanov-a** [comment]
Fixed in 7456c77.
Available in  [v1.1.0](https://github.com/ADCI/webpack-starter-kit/releases/tag/v1.1.0)

Thank you.
