### ISSUE TITLE
Path to load images

### ISSUE THREAD

**Issue by kabala** [ADCI/webpack-starter-kit#2]
Hi,

I don't know the path to load images from pug in dev mode. i used "img/image.jpg"  and "assets/image.jpg" but it doesn't work.

**Comment by guryanov-a** [comment]
Hello, @kabala .

You should consider `src/pug` folder as root folder and write path to `src/img`. So, your path should look like this - `../img/image.jpg`. The same for styles and etc in any mode.
Please, let me know if it helps or if you need any other explanations.

**Comment by kabala** [comment]
Yes, It works!
