### ISSUE TITLE
Problem with spritesmith

### ISSUE THREAD

**Issue by spokospace** [ADCI/webpack-starter-kit#5]
When I'm using spritesmith in output css I have code:

`/* Sprites */
/*
SCSS variables are information about icon's compiled state, stored under its original file name

.icon-home {
  width: $icon-home-width;
}

The large array-like variables contain all information about a single icon
$icon-home: x y offset_x offset_y width height total_width total_height image_path;
*/
/*
The provided mixins are intended to be used with the array-like variables

.icon-home {
  @include sprite-width($icon-home);
}

.icon-email {
  @include sprite($icon-email);
}
*/`

how to disable comments from spritesmith?

**Comment by guryanov-a** [comment]
@CNK001 
Hello. 
They are outputted only in development mode, use `npm run build:prod` to build production version and they will disappear. 
I think it's ok when they are outputted in development mode, anyway these styles are generated by [spritesmith-cli](https://github.com/bevacqua/spritesmith-cli) and I haven't found any option related to disabling comments.

**Comment by spokospace** [comment]
Thx, I'm using this: https://www.npmjs.com/package/webpack-spritesmith
currently I'm trying to set responsive sprites (based on percentage)
